Vagrant::Config.run do |config|
  config.ssh.username = "root"
  config.vm.box = "dev-precise"
  config.vm.network :hostonly, "192.168.88.101"
  config.vm.provision :shell, :path => "provision.sh"
end
