Vagrant::Config.run do |config|
  config.ssh.username = "root"
  config.vm.box = "dev-precise"
  config.vm.network :hostonly, "xxx.xxx.xxx.xxx"
  config.vm.provision :shell, :path => "provision.sh", :args => "one two"
end
